---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-pv
  labels:
    type: local
spec:
  storageClassName: rabbit
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/queues/rabbitmq"